projects:
  libkinetic:
    path: libkinetic
    type: library
    model: virion
    libs:
    - src: SOF3/await-generator/await-generator
      version: ^2.0.0
      epitope: .sha
    - src: SOF3/FormAPI/FormAPI
      version: ^101.4.0
      epitope: .sha
